// ============ about/page.tsx ============
import Navbar from "@/components/Navbar";
import Link from "next/link";

export const metadata = {
  title: "About Us | RewordlyAI",
  description: "Learn about RewordlyAI — free AI writing tools for everyone.",
};

export default function AboutPage() {
  return (
    <div className="min-h-screen bg-gray-950 text-white">
      <Navbar />
      <div className="max-w-3xl mx-auto px-4 py-16">
        <h1 className="text-4xl font-bold mb-6">About RewordlyAI</h1>
        <div className="space-y-6 text-gray-300 leading-relaxed">
          <p>
            <strong className="text-white">RewordlyAI</strong> is a free AI-powered writing platform
            built to help students, professionals, content creators, and everyday writers create
            better content faster.
          </p>
          <p>
            We believe great writing shouldn&apos;t require expensive subscriptions. Our AI tools handle
            everything from grammar correction to full blog post generation — all for free.
          </p>
          <h2 className="text-2xl font-semibold text-white mt-10">Our Technology</h2>
          <p>
            Powered by Llama 3.3 70B and Gemini 1.5 Pro through our unique 3-Agent verification system.
            Every response is independently generated by 3 AI agents and the majority answer is selected —
            giving you significantly higher accuracy than single-model tools.
          </p>
          <h2 className="text-2xl font-semibold text-white mt-8">Privacy & Safety</h2>
          <p>
            Text submitted to our tools is processed in real-time and not stored permanently.
            We implement rate limiting and anti-abuse filters to maintain a safe platform for all users.
          </p>
          <div className="mt-10 p-5 bg-gray-900 rounded-2xl border border-gray-800">
            <p className="text-gray-400 text-sm">
              Questions?{" "}
              <Link href="/contact" className="text-violet-400 hover:underline">Contact us</Link>
              {" "}— we&apos;d love to hear from you.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}