import Navbar from "@/components/Navbar";
import Link from "next/link";

export const metadata = {
  title: "About Us | BantuGwehAI",
  description: "Learn about BantuGwehAI — free AI writing tools powered by 3-agent verification for everyone.",
};

export default function AboutPage() {
  return (
    <div style={{ minHeight: "100vh", background: "#0a0a12", color: "#e8e6f0" }}>
      <Navbar />

      <div className="cyber-grid-bg" style={{
        position: "relative", overflow: "hidden",
        borderBottom: "1px solid #2a254520",
        padding: "48px 20px 40px", textAlign: "center",
        background: "radial-gradient(ellipse at 50% 0%, #7c3aed10 0%, transparent 60%), #0a0a12",
      }}>
        <div style={{ position: "relative", zIndex: 1 }}>
          <h1 style={{
            fontFamily: "'Orbitron', monospace",
            fontSize: 40, fontWeight: 900, marginBottom: 12,
            background: "linear-gradient(135deg, #e8e6f0, #a855f7, #e040fb)",
            WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent",
          }}>
            About BantuGwehAI
          </h1>
          <p style={{ color: "#8b85a8", fontSize: 16, maxWidth: 500, margin: "0 auto" }}>
            Free AI writing tools powered by 3-agent verification
          </p>
        </div>
      </div>

      <div style={{ maxWidth: 720, margin: "0 auto", padding: "40px 20px" }}>
        <div style={{ display: "flex", flexDirection: "column", gap: 24 }}>
          <div style={{
            background: "#13111f", border: "1px solid #2a254530",
            borderRadius: 16, padding: "28px",
          }}>
            <p style={{ color: "#8b85a8", lineHeight: 1.8, fontSize: 15 }}>
              <strong style={{ color: "#e8e6f0" }}>BantuGwehAI</strong> is a free AI-powered writing platform
              built to help students, professionals, content creators, and everyday writers create
              better content faster.
            </p>
          </div>

          <div style={{
            background: "#13111f", border: "1px solid #2a254530",
            borderRadius: 16, padding: "28px",
          }}>
            <p style={{ color: "#8b85a8", lineHeight: 1.8, fontSize: 15 }}>
              We believe great writing shouldn&apos;t require expensive subscriptions. Our AI tools handle
              everything from grammar correction to full blog post generation — all for free.
            </p>
          </div>

          <div style={{
            background: "#13111f", border: "1px solid #7c3aed25",
            borderRadius: 16, padding: "28px",
            position: "relative", overflow: "hidden",
          }}>
            <div style={{
              position: "absolute", top: 0, left: 0, right: 0, height: 2,
              background: "linear-gradient(90deg, transparent, #a855f7, #e040fb, transparent)",
            }} />
            <h2 style={{
              fontFamily: "'Orbitron', monospace",
              fontSize: 20, fontWeight: 700, marginBottom: 16,
              color: "#c084fc",
            }}>Our Technology</h2>
            <p style={{ color: "#8b85a8", lineHeight: 1.8, fontSize: 15 }}>
              Powered by <strong style={{ color: "#a855f7" }}>Llama 3.3 70B</strong> and{" "}
              <strong style={{ color: "#00e5ff" }}>Gemini 2.0 Flash</strong> through our unique 3-Agent MCP verification system.
              Every response is independently generated by 3 AI agents and the majority answer is selected —
              giving you significantly higher accuracy than single-model tools.
            </p>

            <div className="grid-agents" style={{ marginTop: 20 }}>
              {[
                { icon: "🤖", name: "Groq", desc: "Llama 3.3 70B", color: "#a855f7" },
                { icon: "🧠", name: "Gemini", desc: "2.0 Flash", color: "#00e5ff" },
                { icon: "⚡", name: "OpenRouter", desc: "Free Models", color: "#39ff14" },
              ].map((a) => (
                <div key={a.name} style={{
                  background: "#0d0b1a", borderRadius: 12,
                  padding: "16px", textAlign: "center",
                  border: `1px solid ${a.color}20`,
                }}>
                  <div style={{ fontSize: 24, marginBottom: 6 }}>{a.icon}</div>
                  <div style={{ fontWeight: 700, color: a.color, fontSize: 13 }}>{a.name}</div>
                  <div style={{ fontSize: 11, color: "#5a5477" }}>{a.desc}</div>
                </div>
              ))}
            </div>
          </div>

          <div style={{
            background: "#13111f", border: "1px solid #2a254530",
            borderRadius: 16, padding: "28px",
          }}>
            <h2 style={{
              fontFamily: "'Orbitron', monospace",
              fontSize: 20, fontWeight: 700, marginBottom: 16,
              color: "#e8e6f0",
            }}>Privacy & Safety</h2>
            <p style={{ color: "#8b85a8", lineHeight: 1.8, fontSize: 15 }}>
              Text submitted to our tools is processed in real-time and not stored permanently.
              We implement rate limiting and anti-abuse filters to maintain a safe platform for all users.
            </p>
          </div>

          <div style={{
            background: "#7c3aed10", border: "1px solid #7c3aed30",
            borderRadius: 16, padding: "20px 24px",
            textAlign: "center",
          }}>
            <p style={{ color: "#8b85a8", fontSize: 14 }}>
              Questions?{" "}
              <Link href="/contact" style={{ color: "#c084fc", textDecoration: "underline" }}>Contact us</Link>
              {" "}— we&apos;d love to hear from you.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}